name: cont02
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - ipykernel
  - pip:
      - python-dotenv
      - langchain
      - langchain-core
      - langchain-ollama
      - pandas
      - openpyxl
      - requests
